name: 'Create Terraform Backend File'
description: 'Creates a .tf file for Terraform backend configuration'
inputs:
  bucketName:
    description: 'GCP bucket name'
    required: true
  filePath:
    description: 'Path to save backend.tf file'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
